# Generated by Django 3.1.7 on 2021-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_order_is_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.IntegerField(default=1),
        ),
    ]
